server:
  port: 4000
minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: xxx
  accessKeySecret: xxx
  bucketName: codehive
oss:
  type: aliyun